# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add": "00_core (1).ipynb",
         "test_func": "00_core (1).ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/nbdev_template/"

git_url = "https://github.com/{user}/nbdev_template/tree/master/"

def custom_doc_links(name): return None
