# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['add', 'test_func']

# Cell
def add(a,b):
  """add a and b to a sum"""
  return a+b

# Cell
def test_func():
  return 'test'