# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core (1).ipynb (unless otherwise specified).

__all__ = ['add', 'test_func']

# Cell
def add(a,b):
  """sum a and b"""
  return a+b

# Cell
def test_func():
  return 'test'