# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"add": "00_core.ipynb",
         "test_func": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://{user}.github.io/{lib_name}/"

git_url = "https://github.com/{user}/{lib_name}/tree/master/"

def custom_doc_links(name): return None
